apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-multitool
spec:
  replicas: {{ .Values.multitool.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-multitool
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-multitool
    spec:
      containers:
        - name: multitool
          image: {{ .Values.multitool.image }}
          ports:
            - containerPort: {{ .Values.multitool.port }}
          env:
            - name: HTTP_PORT
              value: {{ .Values.multitool.httpPort | quote }}