apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-svc
spec:
  selector:
    app: {{ .Release.Name }}-web
  ports:
    - port: 80
      targetPort: {{ .Values.web.port }}
  type: NodePort